use ux::{u6, u12, u18};

#[derive(Debug, Clone)]
pub enum Instruction {
    CMAL { y: u12 },
    CMALB { y: u12 },
    SLSU { y: u12 },
    SLSUB { y: u12 },
    CMSK { y: u12 },
    CMSKB { y: u12 },
    ENTAU { y: u12 },
    ENTAUB { y: u12 },
    ENTAL { y: u12 },
    ENTALB { y: u12 },
    ADDAL { y: u12 },
    ADDALB { y: u12 },
    SUBAL { y: u12 },
    SUBALB { y: u12 },
    ADDA { y: u12 },
    ADDAB { y: u12 },
    SUBA { y: u12 },
    SUBAB { y: u12 },
    MULAL { y: u12 },
    MULALB { y: u12 },
    DIVA { y: u12 },
    DIVAB { y: u12 },
    IRJP { y: u12 },
    IRJPB { y: u12 },
    ENTB { y: u12 },
    ENTBB { y: u12 },
    JP { y: u12 },
    JPB { y: u12 },
    ENTBK { u: u12 },
    ENTBKB { u: u12 },
    CL { y: u12 },
    CLB { y: u12 },
    STRB { y: u12 },
    STRBB { y: u12 },
    STRAL { y: u12 },
    STRALB { y: u12 },
    STRAU { y: u12 },
    STRAUB { y: u12 },
    SLSET { y: u12 },
    SLCL { y: u12 },
    SLCP { y: u12 },
    IJPEI { y: u12 },
    IJP { y: u12 },
    BSK { y: u12 },
    ISK { y: u12 },
    JPAUZ { y: u12 },
    JPALZ { y: u12 },
    JPAUNZ { y: u12 },
    JPALNZ { y: u12 },
    JPAUP { y: u12 },
    JPALP { y: u12 },
    JPAUNG { y: u12 },
    JPALNG { y: u12 },
    ENTALK { u: u12 },
    ADDALK { u: u12 },
    STRICR { y: u12 },
    BJP { y: u12 },
    STRADR { y: u12 },
    STRSR { y: u12 },
    RJP { y: u12 },
    SIN,
    SOUT,
    SEXF,
    IN { k: u6 },
    OUT { k: u6 },
    EXF { k: u6 },
    RTC,
    INSTP { k: u6 },
    OUTSTP { k: u6 },
    EXFSTP { k: u6 },
    SRSM,
    SKPIIN { k: u6 },
    SKPOIN { k: u6 },
    SKPFIN { k: u6 },
    WTFI,
    OUTOV { k: u6 },
    EXFOV { k: u6 },
    RIL,
    EXL,
    SIL,
    SXL,
    RSHAU { k: u6 },
    RSHAL { k: u6 },
    RSHA { k: u6 },
    SF { k: u6 },
    LSHAU { k: u6 },
    LSHAL { k: u6 },
    LSHA { k: u6 },
    SKP { k: u6 },
    SKPNBO,
    SKPOV,
    SKPNOV,
    SKPODD,
    SKPEVN,
    STOP { k: u6 },
    SKPNR,
    RND,
    CPAL,
    CPAU,
    CPA,
    ENTICR { k: u6 },
    ENTSR { k: u6 },
}

impl Instruction {
    pub fn parse(code: u18) -> Option<Self> {
        let upper_bits: u18 = u18::try_from(0b111_111_000_000_000_000u32).unwrap();
        let middle_bits: u18 = u18::try_from(0b000_000_111_111_000_000u32).unwrap();
        let lower_bits: u18 = u18::try_from(0b000_000_000_000_111_111u32).unwrap();

        let lower12_bits = u12::try_from((code & (middle_bits | lower_bits)) >> 0).unwrap();

        let upper_bits = (code & upper_bits) >> 12;
        let middle_bits = (code & middle_bits) >> 6;
        let lower_bits = u6::try_from((code & lower_bits) >> 0).unwrap();

        let y = lower12_bits;
        let u = lower12_bits;

        let k = lower_bits;

        match (
            u32::try_from(upper_bits).unwrap(),
            u32::try_from(middle_bits).unwrap(),
        ) {
            (0o02, _) => Some(Instruction::CMAL { y }),
            (0o03, _) => Some(Instruction::CMALB { y }),
            (0o04, _) => Some(Instruction::SLSU { y }),
            (0o05, _) => Some(Instruction::SLSUB { y }),
            (0o06, _) => Some(Instruction::CMSK { y }),
            (0o07, _) => Some(Instruction::CMSKB { y }),
            (0o10, _) => Some(Instruction::ENTAU { y }),
            (0o11, _) => Some(Instruction::ENTAUB { y }),
            (0o12, _) => Some(Instruction::ENTAL { y }),
            (0o13, _) => Some(Instruction::ENTALB { y }),
            (0o14, _) => Some(Instruction::ADDAL { y }),
            (0o15, _) => Some(Instruction::ADDALB { y }),
            (0o16, _) => Some(Instruction::SUBAL { y }),
            (0o17, _) => Some(Instruction::SUBALB { y }),
            (0o20, _) => Some(Instruction::ADDA { y }),
            (0o21, _) => Some(Instruction::ADDAB { y }),
            (0o22, _) => Some(Instruction::SUBA { y }),
            (0o23, _) => Some(Instruction::SUBAB { y }),
            (0o24, _) => Some(Instruction::MULAL { y }),
            (0o25, _) => Some(Instruction::MULALB { y }),
            (0o26, _) => Some(Instruction::DIVA { y }),
            (0o27, _) => Some(Instruction::DIVAB { y }),
            (0o30, _) => Some(Instruction::IRJP { y }),
            (0o31, _) => Some(Instruction::IRJPB { y }),
            (0o32, _) => Some(Instruction::ENTB { y }),
            (0o33, _) => Some(Instruction::ENTBB { y }),
            (0o34, _) => Some(Instruction::JP { y }),
            (0o35, _) => Some(Instruction::JPB { y }),
            (0o36, _) => Some(Instruction::ENTBK { u }),
            (0o37, _) => Some(Instruction::ENTBKB { u }),
            (0o40, _) => Some(Instruction::CL { y }),
            (0o41, _) => Some(Instruction::CLB { y }),
            (0o42, _) => Some(Instruction::STRB { y }),
            (0o43, _) => Some(Instruction::STRBB { y }),
            (0o44, _) => Some(Instruction::STRAL { y }),
            (0o45, _) => Some(Instruction::STRALB { y }),
            (0o46, _) => Some(Instruction::STRAU { y }),
            (0o47, _) => Some(Instruction::STRAUB { y }),
            (0o50, 0o01) => Some(Instruction::SIN),
            (0o50, 0o02) => Some(Instruction::SOUT),
            (0o50, 0o03) => Some(Instruction::SEXF),
            (0o50, 0o11) => Some(Instruction::IN { k }),
            (0o50, 0o12) => Some(Instruction::OUT { k }),
            (0o50, 0o13) => Some(Instruction::EXF { k }),
            (0o50, 0o14) => Some(Instruction::RTC),
            (0o50, 0o15) => Some(Instruction::INSTP { k }),
            (0o50, 0o16) => Some(Instruction::OUTSTP { k }),
            (0o50, 0o17) => Some(Instruction::EXFSTP { k }),
            (0o50, 0o20) => Some(Instruction::SRSM),
            (0o50, 0o21) => Some(Instruction::SKPIIN { k }),
            (0o50, 0o22) => Some(Instruction::SKPOIN { k }),
            (0o50, 0o23) => Some(Instruction::SKPFIN { k }),
            (0o50, 0o24) => Some(Instruction::WTFI),
            (0o50, 0o26) => Some(Instruction::OUTOV { k }),
            (0o50, 0o27) => Some(Instruction::EXFOV { k }),
            (0o50, 0o30) => Some(Instruction::RIL),
            (0o50, 0o32) => Some(Instruction::EXL),
            (0o50, 0o34) => Some(Instruction::SIL),
            (0o50, 0o36) => Some(Instruction::SXL),
            (0o50, 0o41) => Some(Instruction::RSHAU { k }),
            (0o50, 0o42) => Some(Instruction::RSHAL { k }),
            (0o50, 0o43) => Some(Instruction::RSHA { k }),
            (0o50, 0o44) => Some(Instruction::SF { k }),
            (0o50, 0o45) => Some(Instruction::LSHAU { k }),
            (0o50, 0o46) => Some(Instruction::LSHAL { k }),
            (0o50, 0o47) => Some(Instruction::LSHA { k }),
            (0o50, 0o50) => Some(Instruction::SKP { k }),
            (0o50, 0o51) => Some(Instruction::SKPNBO),
            (0o50, 0o52) => Some(Instruction::SKPOV),
            (0o50, 0o53) => Some(Instruction::SKPNOV),
            (0o50, 0o54) => Some(Instruction::SKPODD),
            (0o50, 0o55) => Some(Instruction::SKPEVN),
            (0o50, 0o56) => Some(Instruction::STOP { k }),
            (0o50, 0o57) => Some(Instruction::SKPNR),
            (0o50, 0o60) => Some(Instruction::RND),
            (0o50, 0o61) => Some(Instruction::CPAL),
            (0o50, 0o62) => Some(Instruction::CPAU),
            (0o50, 0o63) => Some(Instruction::CPA),
            (0o50, 0o72) => Some(Instruction::ENTICR { k }),
            (0o50, 0o73) => Some(Instruction::ENTSR { k }),
            (0o51, _) => Some(Instruction::SLSET { y }),
            (0o52, _) => Some(Instruction::SLCL { y }),
            (0o53, _) => Some(Instruction::SLCP { y }),
            (0o54, _) => Some(Instruction::IJPEI { y }),
            (0o55, _) => Some(Instruction::IJP { y }),
            (0o56, _) => Some(Instruction::BSK { y }),
            (0o57, _) => Some(Instruction::ISK { y }),
            (0o60, _) => Some(Instruction::JPAUZ { y }),
            (0o61, _) => Some(Instruction::JPALZ { y }),
            (0o62, _) => Some(Instruction::JPAUNZ { y }),
            (0o63, _) => Some(Instruction::JPALNZ { y }),
            (0o64, _) => Some(Instruction::JPAUP { y }),
            (0o65, _) => Some(Instruction::JPALP { y }),
            (0o66, _) => Some(Instruction::JPAUNG { y }),
            (0o67, _) => Some(Instruction::JPALNG { y }),
            (0o70, _) => Some(Instruction::ENTALK { u }),
            (0o71, _) => Some(Instruction::ADDALK { u }),
            (0o72, _) => Some(Instruction::STRICR { y }),
            (0o73, _) => Some(Instruction::BJP { y }),
            (0o74, _) => Some(Instruction::STRADR { y }),
            (0o75, _) => Some(Instruction::STRSR { y }),
            (0o76, _) => Some(Instruction::RJP { y }),
            _ => None,
        }
    }

    pub fn parse_string(string: &str) -> Option<Self> {
        let zero = u6::try_from(0u8).unwrap();

        match string {
            "CMAL" => Some(Instruction::CMAL { y: zero.into() }),
            "CMALB" => Some(Instruction::CMALB { y: zero.into() }),
            "SLSU" => Some(Instruction::SLSU { y: zero.into() }),
            "SLSUB" => Some(Instruction::SLSUB { y: zero.into() }),
            "CMSK" => Some(Instruction::CMSK { y: zero.into() }),
            "CMSKB" => Some(Instruction::CMSKB { y: zero.into() }),
            "ENTAU" => Some(Instruction::ENTAU { y: zero.into() }),
            "ENTAUB" => Some(Instruction::ENTAUB { y: zero.into() }),
            "ENTAL" => Some(Instruction::ENTAL { y: zero.into() }),
            "ENTALB" => Some(Instruction::ENTALB { y: zero.into() }),
            "ADDAL" => Some(Instruction::ADDAL { y: zero.into() }),
            "ADDALB" => Some(Instruction::ADDALB { y: zero.into() }),
            "SUBAL" => Some(Instruction::SUBAL { y: zero.into() }),
            "SUBALB" => Some(Instruction::SUBALB { y: zero.into() }),
            "ADDA" => Some(Instruction::ADDA { y: zero.into() }),
            "ADDAB" => Some(Instruction::ADDAB { y: zero.into() }),
            "SUBA" => Some(Instruction::SUBA { y: zero.into() }),
            "SUBAB" => Some(Instruction::SUBAB { y: zero.into() }),
            "MULAL" => Some(Instruction::MULAL { y: zero.into() }),
            "MULALB" => Some(Instruction::MULALB { y: zero.into() }),
            "DIVA" => Some(Instruction::DIVA { y: zero.into() }),
            "DIVAB" => Some(Instruction::DIVAB { y: zero.into() }),
            "IRJP" => Some(Instruction::IRJP { y: zero.into() }),
            "IRJPB" => Some(Instruction::IRJPB { y: zero.into() }),
            "ENTB" => Some(Instruction::ENTB { y: zero.into() }),
            "ENTBB" => Some(Instruction::ENTBB { y: zero.into() }),
            "JP" => Some(Instruction::JP { y: zero.into() }),
            "JPB" => Some(Instruction::JPB { y: zero.into() }),
            "ENTBK" => Some(Instruction::ENTBK { u: zero.into() }),
            "ENTBKB" => Some(Instruction::ENTBKB { u: zero.into() }),
            "CL" => Some(Instruction::CL { y: zero.into() }),
            "CLB" => Some(Instruction::CLB { y: zero.into() }),
            "STRB" => Some(Instruction::STRB { y: zero.into() }),
            "STRBB" => Some(Instruction::STRBB { y: zero.into() }),
            "STRAL" => Some(Instruction::STRAL { y: zero.into() }),
            "STRALB" => Some(Instruction::STRALB { y: zero.into() }),
            "STRAU" => Some(Instruction::STRAU { y: zero.into() }),
            "STRAUB" => Some(Instruction::STRAUB { y: zero.into() }),
            "SIN" => Some(Instruction::SIN),
            "SOUT" => Some(Instruction::SOUT),
            "SEXF" => Some(Instruction::SEXF),
            "IN" => Some(Instruction::IN { k: zero.into() }),
            "OUT" => Some(Instruction::OUT { k: zero.into() }),
            "EXF" => Some(Instruction::EXF { k: zero.into() }),
            "RTC" => Some(Instruction::RTC),
            "INSTP" => Some(Instruction::INSTP { k: zero.into() }),
            "OUTSTP" => Some(Instruction::OUTSTP { k: zero.into() }),
            "EXFSTP" => Some(Instruction::EXFSTP { k: zero.into() }),
            "SRSM" => Some(Instruction::SRSM),
            "SKPIIN" => Some(Instruction::SKPIIN { k: zero.into() }),
            "SKPOIN" => Some(Instruction::SKPOIN { k: zero.into() }),
            "SKPFIN" => Some(Instruction::SKPFIN { k: zero.into() }),
            "WTFI" => Some(Instruction::WTFI),
            "OUTOV" => Some(Instruction::OUTOV { k: zero.into() }),
            "EXFOV" => Some(Instruction::EXFOV { k: zero.into() }),
            "RIL" => Some(Instruction::RIL),
            "EXL" => Some(Instruction::EXL),
            "SIL" => Some(Instruction::SIL),
            "SXL" => Some(Instruction::SXL),
            "RSHAU" => Some(Instruction::RSHAU { k: zero.into() }),
            "RSHAL" => Some(Instruction::RSHAL { k: zero.into() }),
            "RSHA" => Some(Instruction::RSHA { k: zero.into() }),
            "SF" => Some(Instruction::SF { k: zero.into() }),
            "LSHAU" => Some(Instruction::LSHAU { k: zero.into() }),
            "LSHAL" => Some(Instruction::LSHAL { k: zero.into() }),
            "LSHA" => Some(Instruction::LSHA { k: zero.into() }),
            "SKP" => Some(Instruction::SKP { k: zero.into() }),
            "SKPNBO" => Some(Instruction::SKPNBO),
            "SKPOV" => Some(Instruction::SKPOV),
            "SKPNOV" => Some(Instruction::SKPNOV),
            "SKPODD" => Some(Instruction::SKPODD),
            "SKPEVN" => Some(Instruction::SKPEVN),
            "STOP" => Some(Instruction::STOP { k: zero.into() }),
            "SKPNR" => Some(Instruction::SKPNR),
            "RND" => Some(Instruction::RND),
            "CPAL" => Some(Instruction::CPAL),
            "CPAU" => Some(Instruction::CPAU),
            "CPA" => Some(Instruction::CPA),
            "ENTICR" => Some(Instruction::ENTICR { k: zero.into() }),
            "ENTSR" => Some(Instruction::ENTSR { k: zero.into() }),
            "SLSET" => Some(Instruction::SLSET { y: zero.into() }),
            "SLCL" => Some(Instruction::SLCL { y: zero.into() }),
            "SLCP" => Some(Instruction::SLCP { y: zero.into() }),
            "IJPEI" => Some(Instruction::IJPEI { y: zero.into() }),
            "IJP" => Some(Instruction::IJP { y: zero.into() }),
            "BSK" => Some(Instruction::BSK { y: zero.into() }),
            "ISK" => Some(Instruction::ISK { y: zero.into() }),
            "JPAUZ" => Some(Instruction::JPAUZ { y: zero.into() }),
            "JPALZ" => Some(Instruction::JPALZ { y: zero.into() }),
            "JPAUNZ" => Some(Instruction::JPAUNZ { y: zero.into() }),
            "JPALNZ" => Some(Instruction::JPALNZ { y: zero.into() }),
            "JPAUP" => Some(Instruction::JPAUP { y: zero.into() }),
            "JPALP" => Some(Instruction::JPALP { y: zero.into() }),
            "JPAUNG" => Some(Instruction::JPAUNG { y: zero.into() }),
            "JPALNG" => Some(Instruction::JPALNG { y: zero.into() }),
            "ENTALK" => Some(Instruction::ENTALK { u: zero.into() }),
            "ADDALK" => Some(Instruction::ADDALK { u: zero.into() }),
            "STRICR" => Some(Instruction::STRICR { y: zero.into() }),
            "BJP" => Some(Instruction::BJP { y: zero.into() }),
            "STRADR" => Some(Instruction::STRADR { y: zero.into() }),
            "STRSR" => Some(Instruction::STRSR { y: zero.into() }),
            "RJP" => Some(Instruction::RJP { y: zero.into() }),
            _ => None,
        }
    }

    pub fn name(&self) -> String {
        let str = format!("{:?}", self);
        let (output, _) = str.split_once(' ').unwrap();
        String::from(output)
    }

    pub fn with_operand(self, operand: u18) -> Self {
        let lower6_bits: u18 = u18::try_from(0b000_000_000_000_111_111u32).unwrap();
        let lower12_bits: u18 = u18::try_from(0b000_000_111_111_111_111u32).unwrap();

        match self {
            Instruction::CMAL { y: _ } => Instruction::CMAL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::CMALB { y: _ } => Instruction::CMALB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SLSU { y: _ } => Instruction::SLSU {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SLSUB { y: _ } => Instruction::SLSUB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::CMSK { y: _ } => Instruction::CMSK {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::CMSKB { y: _ } => Instruction::CMSKB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTAU { y: _ } => Instruction::ENTAU {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTAUB { y: _ } => Instruction::ENTAUB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTAL { y: _ } => Instruction::ENTAL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTALB { y: _ } => Instruction::ENTALB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ADDAL { y: _ } => Instruction::ADDAL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ADDALB { y: _ } => Instruction::ADDALB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SUBAL { y: _ } => Instruction::SUBAL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SUBALB { y: _ } => Instruction::SUBALB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ADDA { y: _ } => Instruction::ADDA {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ADDAB { y: _ } => Instruction::ADDAB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SUBA { y: _ } => Instruction::SUBA {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SUBAB { y: _ } => Instruction::SUBAB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::MULAL { y: _ } => Instruction::MULAL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::MULALB { y: _ } => Instruction::MULALB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::DIVA { y: _ } => Instruction::DIVA {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::DIVAB { y: _ } => Instruction::DIVAB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::IRJP { y: _ } => Instruction::IRJP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::IRJPB { y: _ } => Instruction::IRJPB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTB { y: _ } => Instruction::ENTB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTBB { y: _ } => Instruction::ENTBB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JP { y: _ } => Instruction::JP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPB { y: _ } => Instruction::JPB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTBK { u: _ } => Instruction::ENTBK {
                u: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTBKB { u: _ } => Instruction::ENTBKB {
                u: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::CL { y: _ } => Instruction::CL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::CLB { y: _ } => Instruction::CLB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRB { y: _ } => Instruction::STRB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRBB { y: _ } => Instruction::STRBB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRAL { y: _ } => Instruction::STRAL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRALB { y: _ } => Instruction::STRALB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRAU { y: _ } => Instruction::STRAU {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRAUB { y: _ } => Instruction::STRAUB {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SLSET { y: _ } => Instruction::SLSET {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SLCL { y: _ } => Instruction::SLCL {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SLCP { y: _ } => Instruction::SLCP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::IJPEI { y: _ } => Instruction::IJPEI {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::IJP { y: _ } => Instruction::IJP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::BSK { y: _ } => Instruction::BSK {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ISK { y: _ } => Instruction::ISK {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPAUZ { y: _ } => Instruction::JPAUZ {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPALZ { y: _ } => Instruction::JPALZ {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPAUNZ { y: _ } => Instruction::JPAUNZ {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPALNZ { y: _ } => Instruction::JPALNZ {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPAUP { y: _ } => Instruction::JPAUP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPALP { y: _ } => Instruction::JPALP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPAUNG { y: _ } => Instruction::JPAUNG {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::JPALNG { y: _ } => Instruction::JPALNG {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ENTALK { u: _ } => Instruction::ENTALK {
                u: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::ADDALK { u: _ } => Instruction::ADDALK {
                u: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRICR { y: _ } => Instruction::STRICR {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::BJP { y: _ } => Instruction::BJP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRADR { y: _ } => Instruction::STRADR {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::STRSR { y: _ } => Instruction::STRSR {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::RJP { y: _ } => Instruction::RJP {
                y: u12::try_from(operand & lower12_bits).unwrap(),
            },
            Instruction::SIN => Instruction::SIN,
            Instruction::SOUT => Instruction::SOUT,
            Instruction::SEXF => Instruction::SEXF,
            Instruction::IN { k: _ } => Instruction::IN {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::OUT { k: _ } => Instruction::OUT {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::EXF { k: _ } => Instruction::EXF {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::RTC => Instruction::RTC,
            Instruction::INSTP { k: _ } => Instruction::INSTP {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::OUTSTP { k: _ } => Instruction::OUTSTP {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::EXFSTP { k: _ } => Instruction::EXFSTP {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SRSM => Instruction::SRSM,
            Instruction::SKPIIN { k: _ } => Instruction::SKPIIN {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SKPOIN { k: _ } => Instruction::SKPOIN {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SKPFIN { k: _ } => Instruction::SKPFIN {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::WTFI => Instruction::WTFI,
            Instruction::OUTOV { k: _ } => Instruction::OUTOV {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::EXFOV { k: _ } => Instruction::EXFOV {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::RIL => Instruction::RIL,
            Instruction::EXL => Instruction::EXL,
            Instruction::SIL => Instruction::SIL,
            Instruction::SXL => Instruction::SXL,
            Instruction::RSHAU { k: _ } => Instruction::RSHAU {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::RSHAL { k: _ } => Instruction::RSHAL {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::RSHA { k: _ } => Instruction::RSHA {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SF { k: _ } => Instruction::SF {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::LSHAU { k: _ } => Instruction::LSHAU {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::LSHAL { k: _ } => Instruction::LSHAL {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::LSHA { k: _ } => Instruction::LSHA {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SKP { k: _ } => Instruction::SKP {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SKPNBO => Instruction::SKPNBO,
            Instruction::SKPOV => Instruction::SKPOV,
            Instruction::SKPNOV => Instruction::SKPNOV,
            Instruction::SKPODD => Instruction::SKPODD,
            Instruction::SKPEVN => Instruction::SKPEVN,
            Instruction::STOP { k: _ } => Instruction::STOP {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::SKPNR => Instruction::SKPNR,
            Instruction::RND => Instruction::RND,
            Instruction::CPAL => Instruction::CPAL,
            Instruction::CPAU => Instruction::CPAU,
            Instruction::CPA => Instruction::CPA,
            Instruction::ENTICR { k: _ } => Instruction::ENTICR {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
            Instruction::ENTSR { k: _ } => Instruction::ENTSR {
                k: u6::try_from(operand & lower6_bits).unwrap(),
            },
        }
    }

    pub fn encode(&self) -> u18 {
        let code = match self {
            Instruction::CMAL { y } => 0o020000u32 | u32::from(*y),
            Instruction::CMALB { y } => 0o030000u32 | u32::from(*y),
            Instruction::SLSU { y } => 0o040000u32 | u32::from(*y),
            Instruction::SLSUB { y } => 0o050000u32 | u32::from(*y),
            Instruction::CMSK { y } => 0o060000u32 | u32::from(*y),
            Instruction::CMSKB { y } => 0o070000u32 | u32::from(*y),
            Instruction::ENTAU { y } => 0o100000u32 | u32::from(*y),
            Instruction::ENTAUB { y } => 0o110000u32 | u32::from(*y),
            Instruction::ENTAL { y } => 0o120000u32 | u32::from(*y),
            Instruction::ENTALB { y } => 0o130000u32 | u32::from(*y),
            Instruction::ADDAL { y } => 0o140000u32 | u32::from(*y),
            Instruction::ADDALB { y } => 0o150000u32 | u32::from(*y),
            Instruction::SUBAL { y } => 0o160000u32 | u32::from(*y),
            Instruction::SUBALB { y } => 0o170000u32 | u32::from(*y),
            Instruction::ADDA { y } => 0o200000u32 | u32::from(*y),
            Instruction::ADDAB { y } => 0o210000u32 | u32::from(*y),
            Instruction::SUBA { y } => 0o220000u32 | u32::from(*y),
            Instruction::SUBAB { y } => 0o230000u32 | u32::from(*y),
            Instruction::MULAL { y } => 0o240000u32 | u32::from(*y),
            Instruction::MULALB { y } => 0o250000u32 | u32::from(*y),
            Instruction::DIVA { y } => 0o260000u32 | u32::from(*y),
            Instruction::DIVAB { y } => 0o270000u32 | u32::from(*y),
            Instruction::IRJP { y } => 0o300000u32 | u32::from(*y),
            Instruction::IRJPB { y } => 0o310000u32 | u32::from(*y),
            Instruction::ENTB { y } => 0o320000u32 | u32::from(*y),
            Instruction::ENTBB { y } => 0o330000u32 | u32::from(*y),
            Instruction::JP { y } => 0o340000u32 | u32::from(*y),
            Instruction::JPB { y } => 0o0350000u32 | u32::from(*y),
            Instruction::ENTBK { u } => 0o360000u32 | u32::from(*u),
            Instruction::ENTBKB { u } => 0o0370000u32 | u32::from(*u),
            Instruction::CL { y } => 0o400000u32 | u32::from(*y),
            Instruction::CLB { y } => 0o410000u32 | u32::from(*y),
            Instruction::STRB { y } => 0o420000u32 | u32::from(*y),
            Instruction::STRBB { y } => 0o430000u32 | u32::from(*y),
            Instruction::STRAL { y } => 0o440000u32 | u32::from(*y),
            Instruction::STRALB { y } => 0o450000u32 | u32::from(*y),
            Instruction::STRAU { y } => 0o460000u32 | u32::from(*y),
            Instruction::STRAUB { y } => 0o470000u32 | u32::from(*y),
            Instruction::SLSET { y } => 0o510000u32 | u32::from(*y),
            Instruction::SLCL { y } => 0o520000u32 | u32::from(*y),
            Instruction::SLCP { y } => 0o530000u32 | u32::from(*y),
            Instruction::IJPEI { y } => 0o540000u32 | u32::from(*y),
            Instruction::IJP { y } => 0o550000u32 | u32::from(*y),
            Instruction::BSK { y } => 0o560000u32 | u32::from(*y),
            Instruction::ISK { y } => 0o570000u32 | u32::from(*y),
            Instruction::JPAUZ { y } => 0o600000u32 | u32::from(*y),
            Instruction::JPALZ { y } => 0o610000u32 | u32::from(*y),
            Instruction::JPAUNZ { y } => 0o620000u32 | u32::from(*y),
            Instruction::JPALNZ { y } => 0o630000u32 | u32::from(*y),
            Instruction::JPAUP { y } => 0o640000u32 | u32::from(*y),
            Instruction::JPALP { y } => 0o650000u32 | u32::from(*y),
            Instruction::JPAUNG { y } => 0o660000u32 | u32::from(*y),
            Instruction::JPALNG { y } => 0o670000u32 | u32::from(*y),
            Instruction::ENTALK { u } => 0o700000u32 | u32::from(*u),
            Instruction::ADDALK { u } => 0o710000u32 | u32::from(*u),
            Instruction::STRICR { y } => 0o720000u32 | u32::from(*y),
            Instruction::BJP { y } => 0o730000u32 | u32::from(*y),
            Instruction::STRADR { y } => 0o740000u32 | u32::from(*y),
            Instruction::STRSR { y } => 0o750000u32 | u32::from(*y),
            Instruction::RJP { y } => 0o760000u32 | u32::from(*y),
            Instruction::SIN => 0o500100u32,
            Instruction::SOUT => 0o500200u32,
            Instruction::SEXF => 0o500300u32,
            Instruction::IN { k } => 0o501100u32 | u32::from(*k),
            Instruction::OUT { k } => 0o501200u32 | u32::from(*k),
            Instruction::EXF { k } => 0o501300u32 | u32::from(*k),
            Instruction::RTC => 0o501400u32,
            Instruction::INSTP { k } => 0o501500u32 | u32::from(*k),
            Instruction::OUTSTP { k } => 0o501600u32 | u32::from(*k),
            Instruction::EXFSTP { k } => 0o501700u32 | u32::from(*k),
            Instruction::SRSM => 0o502000u32,
            Instruction::SKPIIN { k } => 0o502100u32 | u32::from(*k),
            Instruction::SKPOIN { k } => 0o502200u32 | u32::from(*k),
            Instruction::SKPFIN { k } => 0o502300u32 | u32::from(*k),
            Instruction::WTFI => 0o502400u32,
            Instruction::OUTOV { k } => 0o502600u32 | u32::from(*k),
            Instruction::EXFOV { k } => 0o502700u32 | u32::from(*k),
            Instruction::RIL => 0o503000u32,
            Instruction::EXL => 0o503200u32,
            Instruction::SIL => 0o503400u32,
            Instruction::SXL => 0o503600u32,
            Instruction::RSHAU { k } => 0o504100u32 | u32::from(*k),
            Instruction::RSHAL { k } => 0o504200u32 | u32::from(*k),
            Instruction::RSHA { k } => 0o504300u32 | u32::from(*k),
            Instruction::SF { k } => 0o504400u32 | u32::from(*k),
            Instruction::LSHAU { k } => 0o504500u32 | u32::from(*k),
            Instruction::LSHAL { k } => 0o504600u32 | u32::from(*k),
            Instruction::LSHA { k } => 0o504700u32 | u32::from(*k),
            Instruction::SKP { k } => 0o505000u32 | u32::from(*k),
            Instruction::SKPNBO => 0o505100u32,
            Instruction::SKPOV => 0o505200u32,
            Instruction::SKPNOV => 0o505300u32,
            Instruction::SKPODD => 0o505400u32,
            Instruction::SKPEVN => 0o505500u32,
            Instruction::STOP { k } => 0o505600u32 | u32::from(*k),
            Instruction::SKPNR => 0o505700u32,
            Instruction::RND => 0o506000u32,
            Instruction::CPAL => 0o506100u32,
            Instruction::CPAU => 0o506200u32,
            Instruction::CPA => 0o506300u32,
            Instruction::ENTICR { k } => 0o507200u32 | u32::from(*k),
            Instruction::ENTSR { k } => 0o507300u32 | u32::from(*k),
        };

        u18::try_from(code).unwrap()
    }

    pub fn microseconds(&self) -> u64 {
        match self {
            Instruction::CMAL { .. } => 4,
            Instruction::CMALB { .. } => 4,
            Instruction::SLSU { .. } => 4,
            Instruction::SLSUB { .. } => 4,
            Instruction::CMSK { .. } => 4,
            Instruction::CMSKB { .. } => 4,
            Instruction::ENTAU { .. } => 4,
            Instruction::ENTAUB { .. } => 4,
            Instruction::ENTAL { .. } => 4,
            Instruction::ENTALB { .. } => 4,
            Instruction::ADDAL { .. } => 4,
            Instruction::ADDALB { .. } => 4,
            Instruction::SUBAL { .. } => 4,
            Instruction::SUBALB { .. } => 4,
            Instruction::ADDA { .. } => 6,
            Instruction::ADDAB { .. } => 6,
            Instruction::SUBA { .. } => 6,
            Instruction::SUBAB { .. } => 6,
            Instruction::MULAL { .. } => 14,
            Instruction::MULALB { .. } => 14,
            Instruction::DIVA { .. } => 14,
            Instruction::DIVAB { .. } => 14,
            Instruction::IRJP { .. } => 6,
            Instruction::IRJPB { .. } => 6,
            Instruction::ENTB { .. } => 4,
            Instruction::ENTBB { .. } => 4,
            Instruction::JP { .. } => 2,
            Instruction::JPB { .. } => 2,
            Instruction::ENTBK { .. } => 2,
            Instruction::ENTBKB { .. } => 2,
            Instruction::CL { .. } => 4,
            Instruction::CLB { .. } => 4,
            Instruction::STRB { .. } => 4,
            Instruction::STRBB { .. } => 4,
            Instruction::STRAL { .. } => 4,
            Instruction::STRALB { .. } => 4,
            Instruction::STRAU { .. } => 4,
            Instruction::STRAUB { .. } => 4,
            Instruction::SLSET { .. } => 4,
            Instruction::SLCL { .. } => 4,
            Instruction::SLCP { .. } => 4,
            Instruction::IJPEI { .. } => 4,
            Instruction::IJP { .. } => 4,
            Instruction::BSK { .. } => 4,
            Instruction::ISK { .. } => 6,
            Instruction::JPAUZ { .. } => 2,
            Instruction::JPALZ { .. } => 2,
            Instruction::JPAUNZ { .. } => 2,
            Instruction::JPALNZ { .. } => 2,
            Instruction::JPAUP { .. } => 2,
            Instruction::JPALP { .. } => 2,
            Instruction::JPAUNG { .. } => 2,
            Instruction::JPALNG { .. } => 2,
            Instruction::ENTALK { .. } => 2,
            Instruction::ADDALK { .. } => 2,
            Instruction::STRICR { .. } => 4,
            Instruction::BJP { .. } => 2,
            Instruction::STRADR { .. } => 4,
            Instruction::STRSR { .. } => 4,
            Instruction::RJP { .. } => 4,
            Instruction::SIN => 2,
            Instruction::SOUT => 2,
            Instruction::SEXF => 2,
            Instruction::IN { .. } => 6,
            Instruction::OUT { .. } => 6,
            Instruction::EXF { .. } => 6,
            Instruction::RTC => 2,
            Instruction::INSTP { .. } => 2,
            Instruction::OUTSTP { .. } => 2,
            Instruction::EXFSTP { .. } => 2,
            Instruction::SRSM => 2,
            Instruction::SKPIIN { .. } => 2,
            Instruction::SKPOIN { .. } => 2,
            Instruction::SKPFIN { .. } => 2,
            Instruction::WTFI => 2,
            Instruction::OUTOV { .. } => 2,
            Instruction::EXFOV { .. } => 2,
            Instruction::RIL => 2,
            Instruction::EXL => 2,
            Instruction::SIL => 2,
            Instruction::SXL => 2,
            Instruction::RSHAU { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::RSHAL { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::RSHA { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::SF { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::LSHAU { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::LSHAL { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::LSHA { k } => 4 + 2 * (u64::from(*k) / 4),
            Instruction::SKP { .. } => 2,
            Instruction::SKPNBO => 2,
            Instruction::SKPOV => 2,
            Instruction::SKPNOV => 2,
            Instruction::SKPODD => 2,
            Instruction::SKPEVN => 2,
            Instruction::STOP { .. } => 2,
            Instruction::SKPNR => 2,
            Instruction::RND => 2,
            Instruction::CPAL => 2,
            Instruction::CPAU => 2,
            Instruction::CPA => 2,
            Instruction::ENTICR { .. } => 2,
            Instruction::ENTSR { .. } => 2,
        }
    }
}
